Repository Kernel360/E2E2-CATCHLINE, pull requests merged in 2024-08, with the labels that each got.

#27 [feat] 식당 구현
  docker-compose.yaml
  src/main/java/org/example/catch_line/restaurant/model/entity/FoodType.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/ServiceType.java
  src/main/java/org/example/catch_line/restaurant/model/entity/readme.md
  src/main/java/org/example/catch_line/restaurant/repository/RestaurantRepository.java
  src/main/java/org/example/catch_line/restaurant/repository/readme.md
  src/main/resources/application.properties
Labels: enhancement

#26 [Featrue]WaitingService,WaitingRequest 구현
  src/main/java/org/example/catch_line/waiting/model/dto/WaitingRequest.java
  src/main/java/org/example/catch_line/waiting/model/entity/WaitingEntity.java
  src/main/java/org/example/catch_line/waiting/model/entity/WaitingType.java
  src/main/java/org/example/catch_line/waiting/service/WaitingService.java
  src/main/resources/application.properties
Labels: enhancement

#32 [fix] restaurant
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/restaurant/repository/RestaurantHourRepository.java
Labels: bug

#34 [Fix] @Transactional 추가
  src/main/java/org/example/catch_line/waiting/model/dto/readme.md
  src/main/java/org/example/catch_line/waiting/model/entity/readme.md
  src/main/java/org/example/catch_line/waiting/repository/readme.md
  src/main/java/org/example/catch_line/waiting/service/readme.md
  src/test/java/org/example/catch_line/waiting/service/WaitingServiceTest.java
Labels: enhancement

#36 [Feat] Reservation Service, Test 구현 완료
  src/main/java/org/example/catch_line/CatchLineApplication.java
  src/main/java/org/example/catch_line/reservation/model/dto/ReservationRequest.java
  src/main/java/org/example/catch_line/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/reservation/validation/ReservationDateValidator.java
  src/main/java/org/example/catch_line/waiting/service/WaitingService.java
  src/test/java/org/example/catch_line/reservation/service/ReservationServiceTest.java
Labels: enhancement

#29 [feat] 일반 사용자 회원가입, 로그인 기능 구현
  src/main/java/org/example/catch_line/member/README.md
  src/main/java/org/example/catch_line/member/controller/MemberController.java
  src/main/java/org/example/catch_line/member/controller/readme.md
  src/main/java/org/example/catch_line/member/model/dto/LoginRequest.java
  src/main/java/org/example/catch_line/member/model/dto/MemberResponse.java
  src/main/java/org/example/catch_line/member/model/dto/SignUpRequest.java
  src/main/java/org/example/catch_line/member/model/dto/readme.md
  src/main/java/org/example/catch_line/member/model/entity/MemberEntity.java
  src/main/java/org/example/catch_line/member/model/entity/readme.md
  src/main/java/org/example/catch_line/member/model/mapper/MemberResponseMapper.java
  src/main/java/org/example/catch_line/member/repository/MemberRepository.java
  src/main/java/org/example/catch_line/member/repository/readme.md
  src/main/java/org/example/catch_line/member/service/MemberService.java
  src/main/java/org/example/catch_line/member/service/readme.md
  src/test/java/org/example/catch_line/member/service/MemberServiceTest.java
Labels: enhancement

#37 [Feature] 식당 서비스 구현
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantCreateRequest.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantResponse.java
  src/main/java/org/example/catch_line/restaurant/model/dto/readme.md
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantMapper.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantService.java
  src/main/java/org/example/catch_line/restaurant/service/readme.md
  src/test/java/org/example/catch_line/restaurant/service/RestaurantServiceTest.java
Labels: enhancement

#38 [refactor] Member Entity에 연관관계 추가
  docker-compose.yaml
  src/main/java/org/example/catch_line/member/model/entity/MemberEntity.java
Labels: enhancement

#39 [feat] entity relation setting
  src/main/java/org/example/catch_line/member/model/entity/MemberEntity.java
  src/main/java/org/example/catch_line/menu/model/entity/MenuEntity.java
  src/main/java/org/example/catch_line/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/review/model/entity/ReviewEntity.java
  src/main/java/org/example/catch_line/waiting/model/entity/WaitingEntity.java
Labels: enhancement

#41 [Refactor] WaitingService refactoring
  src/main/java/org/example/catch_line/waiting/model/entity/WaitingEntity.java
  src/main/java/org/example/catch_line/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/waiting/service/WaitingService.java
  src/test/java/org/example/catch_line/waiting/service/WaitingServiceTest.java
Labels: enhancement

#44 [Feat, Refactor] 테스트 데이터 추가, 식당 로직 수정 및 추가
  docker-compose.yaml
  src/main/java/org/example/catch_line/restaurant/controller/RestaurantController.java
  src/main/java/org/example/catch_line/restaurant/controller/readme.md
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantCreateRequest.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantResponse.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/constant/FoodType.java
  src/main/java/org/example/catch_line/restaurant/model/entity/constant/OpenStatus.java
  src/main/java/org/example/catch_line/restaurant/model/entity/constant/ServiceType.java
  src/main/java/org/example/catch_line/restaurant/repository/RestaurantRepository.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/messages.properties
  src/main/resources/sql/data.sql
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/templates/css/bootstrap.min.css
  src/main/resources/templates/restaurant/restaurant.html
  src/test/java/org/example/catch_line/restaurant/service/RestaurantServiceTest.java
Labels: feat

#45 [refactoring] Member 수정, 회원수정 및 삭제 기능 추가
  src/main/java/org/example/catch_line/common/constant/SessionConst.java
  src/main/java/org/example/catch_line/member/README.md
  src/main/java/org/example/catch_line/member/controller/AuthController.java
  src/main/java/org/example/catch_line/member/controller/MemberController.java
  src/main/java/org/example/catch_line/member/controller/MyReviewController.java
  src/main/java/org/example/catch_line/member/controller/MyScrapController.java
  src/main/java/org/example/catch_line/member/model/dto/MemberResponse.java
  src/main/java/org/example/catch_line/member/model/dto/MemberUpdateRequest.java
  src/main/java/org/example/catch_line/member/model/entity/MemberEntity.java
  src/main/java/org/example/catch_line/member/model/mapper/MemberResponseMapper.java
  src/main/java/org/example/catch_line/member/repository/MemberRepository.java
  src/main/java/org/example/catch_line/member/service/AuthService.java
  src/main/java/org/example/catch_line/member/service/MemberService.java
  src/main/java/org/example/catch_line/member/service/MyReviewService.java
  src/main/java/org/example/catch_line/member/service/MyScrapService.java
  src/main/java/org/example/catch_line/member/validate/MemberValidator.java
  src/main/resources/sql/data.sql
  src/test/java/org/example/catch_line/member/service/AuthServiceTest.java
Labels: enhancement

#51 [Feat] Waiting, Reservation Controller + 간단한 타임리프 폼 구현 완료
  src/main/java/org/example/catch_line/reservation/controller/ReservationController.java
  src/main/java/org/example/catch_line/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/waiting/controller/WaitingController.java
  src/main/java/org/example/catch_line/waiting/controller/readme.md
  src/main/resources/templates/reservation/reservation.html
  src/main/resources/templates/waiting/waiting.html
  src/test/java/org/example/catch_line/reservation/service/ReservationServiceTest.java
  src/test/java/org/example/catch_line/waiting/service/WaitingServiceTest.java
Labels: enhancement

#53 [feature] 스크랩 기능 구현
  docker-compose.yaml
  src/main/java/org/example/catch_line/exception/GlobalExceptionHandler.java
  src/main/java/org/example/catch_line/restaurant/README.md
  src/main/java/org/example/catch_line/restaurant/controller/RestaurantScrapController.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantScrapService.java
  src/main/java/org/example/catch_line/restaurant/validate/RestaurantValidator.java
Labels: enhancement

#58 [Feat] waitingRegistrationId 구현 및 리팩토링
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/history/model/dto/HistoryResponse.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/reservation/controller/ReservationController.java
  src/main/java/org/example/catch_line/reservation/exception/IdException.java
  src/main/java/org/example/catch_line/reservation/exception/ServiceTypeException.java
  src/main/java/org/example/catch_line/reservation/model/dto/ReservationRequest.java
  src/main/java/org/example/catch_line/reservation/model/dto/ReservationResponse.java
  src/main/java/org/example/catch_line/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/waiting/controller/WaitingController.java
  src/main/java/org/example/catch_line/waiting/model/dto/WaitingRequest.java
  src/main/java/org/example/catch_line/waiting/model/dto/WaitingResponse.java
  src/main/java/org/example/catch_line/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/waiting/service/WaitingService.java
  src/main/resources/templates/history/history.html
  src/main/resources/templates/reservation/reservation.html
  src/main/resources/templates/waiting/waiting.html
  src/test/java/org/example/catch_line/reservation/service/ReservationServiceTest.java
  src/test/java/org/example/catch_line/waiting/service/WaitingServiceTest.java
Labels: enhancement

#63 [feat, fix] 식당 프리뷰 구현, 리뷰 수정, 식당 수정
  src/main/java/org/example/catch_line/common/controller/HomeController.java
  src/main/java/org/example/catch_line/menu/model/dto/MenuResponse.java
  src/main/java/org/example/catch_line/menu/model/entity/MenuEntity.java
  src/main/java/org/example/catch_line/menu/model/mapper/MenuMapper.java
  src/main/java/org/example/catch_line/restaurant/controller/RestaurantController.java
  src/main/java/org/example/catch_line/restaurant/controller/RestaurantPreviewController.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantHourResponse.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantPreviewResponse.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantResponse.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/constant/DayOfWeeks.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantHourMapper.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantMapper.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantPreviewMapper.java
  src/main/java/org/example/catch_line/restaurant/repository/RestaurantHourRepository.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantHourService.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantPreviewService.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantService.java
  src/main/java/org/example/catch_line/review/controller/ReviewController.java
  src/main/java/org/example/catch_line/review/model/dto/ReviewResponse.java
  src/main/java/org/example/catch_line/review/model/mapper/ReviewMapper.java
  src/main/java/org/example/catch_line/review/repository/ReviewRepository.java
  src/main/java/org/example/catch_line/review/service/ReviewService.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/menu/menus.html
  src/main/resources/templates/restaurant/restaurant.html
  src/main/resources/templates/restaurant/restaurantPreview.html
Labels: feat

#65 [refactor] Password VO 수정
  build.gradle
  src/main/java/org/example/catch_line/common/SessionUtils.java
  src/main/java/org/example/catch_line/config/SecurityConfig.java
  src/main/java/org/example/catch_line/config/readme.md
  src/main/java/org/example/catch_line/exception/CatchLineException.java
  src/main/java/org/example/catch_line/exception/GlobalExceptionHandler.java
  src/main/java/org/example/catch_line/exception/email/DuplicateEmailException.java
  src/main/java/org/example/catch_line/exception/email/InvalidEmailException.java
  src/main/java/org/example/catch_line/exception/password/InvalidEncodedPasswordException.java
  src/main/java/org/example/catch_line/exception/password/InvalidPasswordException.java
  src/main/java/org/example/catch_line/exception/phone/InvalidPhoneNumberException.java
  src/main/java/org/example/catch_line/exception/session/InvalidSessionException.java
  src/main/java/org/example/catch_line/member/controller/AuthController.java
  src/main/java/org/example/catch_line/member/controller/MemberController.java
  src/main/java/org/example/catch_line/member/model/dto/LoginRequest.java
  src/main/java/org/example/catch_line/member/model/dto/MemberUpdateRequest.java
  src/main/java/org/example/catch_line/member/model/dto/SignUpRequest.java
  src/main/java/org/example/catch_line/member/model/entity/MemberEntity.java
  src/main/java/org/example/catch_line/member/model/mapper/converter/EmailConverter.java
  src/main/java/org/example/catch_line/member/model/mapper/converter/PasswordConverter.java
  src/main/java/org/example/catch_line/member/model/mapper/converter/PhoneNumberConverter.java
  src/main/java/org/example/catch_line/member/model/vo/Email.java
  src/main/java/org/example/catch_line/member/model/vo/Password.java
  src/main/java/org/example/catch_line/member/model/vo/PhoneNumber.java
  src/main/java/org/example/catch_line/member/service/AuthService.java
  src/main/java/org/example/catch_line/member/service/MemberService.java
  src/main/java/org/example/catch_line/member/validate/MemberValidator.java
  src/main/java/org/example/catch_line/member/validate/PasswordValidator.java
  src/main/resources/sql/data.sql
Labels: refactoring

#66 [Feature, Fix] Rating VO 구현 및 리뷰, 식당 수정
  src/main/java/org/example/catch_line/common/model/mapper/RatingConverter.java
  src/main/java/org/example/catch_line/common/model/vo/Rating.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/entity/constant/DayOfWeeks.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantMapper.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantPreviewMapper.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantPreviewService.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantService.java
  src/main/java/org/example/catch_line/review/controller/ReviewController.java
  src/main/java/org/example/catch_line/review/repository/ReviewRepository.java
  src/main/java/org/example/catch_line/review/service/ReviewService.java
  src/main/resources/sql/data.sql
  src/test/java/org/example/catch_line/restaurant/service/RestaurantServiceTest.java
Labels: enhancement, refactoring

#75 [Fix] 식당 테스트 코드 작성
  src/main/java/org/example/catch_line/menu/model/mapper/MenuMapper.java
  src/main/java/org/example/catch_line/menu/model/validation/MenuValidator.java
  src/main/java/org/example/catch_line/menu/service/MenuService.java
  src/main/java/org/example/catch_line/restaurant/controller/RestaurantController.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantResponse.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantMapper.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantHourService.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantPreviewService.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantService.java
  src/main/java/org/example/catch_line/review/service/ReviewService.java
  src/main/java/org/example/catch_line/review/validation/ReviewValidator.java
  src/main/resources/templates/menu/menus.html
  src/main/resources/templates/restaurant/restaurant.html
  src/test/java/org/example/catch_line/menu/service/MenuServiceTest.java
  src/test/java/org/example/catch_line/restaurant/controller/RestaurantControllerTest.java
  src/test/java/org/example/catch_line/restaurant/service/RestaurantHourServiceTest.java
  src/test/java/org/example/catch_line/restaurant/service/RestaurantPreviewServiceTest.java
  src/test/java/org/example/catch_line/restaurant/service/RestaurantServiceTest.java
  src/test/java/org/example/catch_line/review/service/ReviewServiceTest.java
Labels: refactoring

#77 [refactoring] booking,history-Service,Controller-TestCode 작성
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/booking/waiting/service/WaitingService.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/test/java/org/example/catch_line/booking/reservation/controller/ReservationControllerTest.java
  src/test/java/org/example/catch_line/booking/reservation/service/ReservationServiceTest.java
  src/test/java/org/example/catch_line/booking/waiting/controller/WaitingControllerTest.java
  src/test/java/org/example/catch_line/booking/waiting/service/WaitingServiceTest.java
  src/test/java/org/example/catch_line/history/controller/HistoryControllerTest.java
  src/test/java/org/example/catch_line/history/service/HistoryServiceTest.java
  src/test/java/org/example/catch_line/waiting/service/WaitingServiceTest.java
Labels: refactoring

#79 [refactorig] reservationServiceTest 디렉토리 삭제
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/resources/templates/history/reservationDetail.html
  src/test/java/org/example/catch_line/member/service/AuthServiceTest.java
  src/test/java/org/example/catch_line/reservation/service/ReservationServiceTest.java
Labels: refactoring

#81 [Feature] 메뉴, 리뷰, 프리뷰 컨트롤러 테스트 구현
  src/test/java/org/example/catch_line/menu/controller/MenuControllerTest.java
  src/test/java/org/example/catch_line/restaurant/controller/RestaurantPreviewControllerTest.java
  src/test/java/org/example/catch_line/review/controller/ReviewControllerTest.java
Labels: feat

#83 [Feature] 회원 정보 조회 및 수정 ui 구현
  src/main/java/org/example/catch_line/common/readme.md
  src/main/java/org/example/catch_line/member/controller/thymeleaf/AuthController.java
  src/main/java/org/example/catch_line/member/controller/thymeleaf/MemberController.java
  src/main/java/org/example/catch_line/member/model/dto/MemberUpdateRequest.java
  src/main/java/org/example/catch_line/member/model/entity/MemberEntity.java
  src/main/java/org/example/catch_line/member/service/AuthService.java
  src/main/java/org/example/catch_line/member/service/MemberService.java
  src/main/java/org/example/catch_line/member/validation/MemberValidator.java
  src/main/resources/templates/member/memberDetail.html
  src/main/resources/templates/member/memberUpdate.html
  src/test/java/org/example/catch_line/member/service/AuthServiceTest.java
  src/test/java/org/example/catch_line/member/service/MemberServiceTest.java
Labels: enhancement

#82 [Feature] 예약 수정기능 구현 및 타임리프 수정, 전체적인 코드 리팩토링
  src/main/java/org/example/catch_line/CatchLineApplication.java
  src/main/java/org/example/catch_line/booking/reservation/controller/ReservationController.java
  src/main/java/org/example/catch_line/booking/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/booking/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/booking/waiting/controller/WaitingController.java
  src/main/java/org/example/catch_line/booking/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/booking/waiting/service/WaitingService.java
  src/main/java/org/example/catch_line/common/constant/Status.java
  src/main/java/org/example/catch_line/exception/booking/BookingErrorException.java
  src/main/java/org/example/catch_line/exception/booking/ServiceIdException.java
  src/main/java/org/example/catch_line/exception/booking/WaitingException.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/history/validation/HistoryValidator.java
  src/main/resources/application.properties
  src/main/resources/templates/history/history.html
  src/main/resources/templates/history/reservationDetail.html
  src/main/resources/templates/history/waitingDetail.html
  src/main/resources/templates/reservation/updateReservation.html
  src/main/resources/templates/restaurant/restaurantPreview.html
  src/main/resources/templates/waiting/waiting.html
Labels: enhancement

#86 [Feature] Review Controller, Service 구현
  src/main/java/org/example/catch_line/booking/waiting/controller/WaitingController.java
  src/main/java/org/example/catch_line/review/controller/ReviewController.java
  src/main/java/org/example/catch_line/review/model/dto/ReviewCreateRequest.java
  src/main/java/org/example/catch_line/review/model/dto/ReviewResponse.java
  src/main/java/org/example/catch_line/review/model/dto/ReviewUpdateRequest.java
  src/main/java/org/example/catch_line/review/model/entity/ReviewEntity.java
  src/main/java/org/example/catch_line/review/model/mapper/ReviewMapper.java
  src/main/java/org/example/catch_line/review/service/ReviewService.java
  src/main/resources/templates/review/reviewForm.html
  src/main/resources/templates/review/reviewUpdateForm.html
  src/main/resources/templates/review/reviews.html
  src/test/java/org/example/catch_line/review/service/ReviewServiceTest.java
Labels: enhancement

#87 [Refactoring] member role 삭제, preview 수정
  src/main/java/org/example/catch_line/user/member/controller/rest/RestAuthController.java
  src/main/java/org/example/catch_line/user/member/controller/thymeleaf/AuthController.java
  src/main/java/org/example/catch_line/user/member/model/dto/LoginRequest.java
  src/main/java/org/example/catch_line/user/member/model/dto/MemberResponse.java
  src/main/java/org/example/catch_line/user/member/model/dto/SignUpRequest.java
  src/main/java/org/example/catch_line/user/member/model/entity/MemberEntity.java
  src/main/java/org/example/catch_line/user/member/model/mapper/MemberResponseMapper.java
  src/main/java/org/example/catch_line/user/member/repository/MemberRepository.java
  src/main/java/org/example/catch_line/user/member/service/AuthService.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerAuthController.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/memberDetail.html
  src/main/resources/templates/member/signup.html
  src/main/resources/templates/owner/owner.html
  src/main/resources/templates/restaurant/restaurantPreview.html
Labels: refactoring

#88 [Refactoring] refactoring-review-view
  src/main/java/org/example/catch_line/review/model/entity/ReviewEntity.java
  src/main/resources/templates/review/reviews.html
Labels: refactoring

#90 [Feature] owner restaurant 추가 기능 구현
  .gitignore
  src/main/java/org/example/catch_line/common/SessionUtils.java
  src/main/java/org/example/catch_line/restaurant/model/dto/RestaurantCreateRequest.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/restaurant/model/mapper/RestaurantMapper.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/java/org/example/catch_line/user/owner/model/entity/OwnerEntity.java
  src/main/java/org/example/catch_line/user/owner/repository/OwnerRepository.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerService.java
  src/main/resources/application.properties
  src/main/resources/templates/owner/createRestaurant.html
Labels: enhancement

#93 [Feature] ResrevationHourEntity default 값 부여 + Waiting 이슈 처리
  src/main/java/org/example/catch_line/booking/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/restaurant/service/RestaurantHourService.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerService.java
  src/main/resources/sql/data.sql
Labels: enhancement

#94 [Feature] owner 기능 구현
  src/main/java/org/example/catch_line/booking/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/booking/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/restaurant/controller/RestaurantImageController.java
  src/main/java/org/example/catch_line/restaurant/repository/RestaurantHourRepository.java
  src/main/java/org/example/catch_line/restaurant/repository/RestaurantRepository.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerService.java
  src/main/resources/templates/owner/history.html
  src/main/resources/templates/owner/owner.html
  src/main/resources/templates/owner/restaurantList.html
  src/main/resources/templates/restaurant/restaurant.html
Labels: enhancement

#101 [Feature] owner history
  src/main/java/org/example/catch_line/booking/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/booking/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/booking/waiting/service/WaitingService.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerService.java
  src/main/resources/templates/owner/history.html
  src/main/resources/templates/owner/owner.html
  src/main/resources/templates/owner/reservationDetail.html
  src/main/resources/templates/owner/restaurantListHistory.html
  src/main/resources/templates/owner/waitingDetail.html
Labels: enhancement

#100 [Feature] 검색 기능 구현, 프리뷰에 스크랩 수 추가
  src/main/java/org/example/catch_line/dining/restaurant/controller/RestaurantPreviewController.java
  src/main/java/org/example/catch_line/dining/restaurant/model/dto/RestaurantPreviewResponse.java
  src/main/java/org/example/catch_line/dining/restaurant/model/entity/constant/FoodType.java
  src/main/java/org/example/catch_line/dining/restaurant/model/mapper/RestaurantPreviewMapper.java
  src/main/java/org/example/catch_line/dining/restaurant/repository/RestaurantRepository.java
  src/main/java/org/example/catch_line/dining/restaurant/service/RestaurantPreviewService.java
  src/main/java/org/example/catch_line/scrap/model/entity/ScrapEntity.java
  src/main/java/org/example/catch_line/scrap/model/key/ScrapId.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/restaurant/restaurantPreview.html
Labels: enhancement

#106 [Feature] waiting, reservation 수정
  src/main/java/org/example/catch_line/booking/reservation/controller/ReservationController.java
  src/main/java/org/example/catch_line/booking/reservation/model/dto/ReservationRequest.java
  src/main/java/org/example/catch_line/booking/reservation/model/dto/ReservationResponse.java
  src/main/java/org/example/catch_line/booking/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/booking/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/exception/booking/DuplicateReservationTimeException.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/history/validation/HistoryValidator.java
  src/main/resources/templates/reservation/updateReservation.html
Labels: enhancement

#107 [Feature, Refactoring] 알림 기능 구현
  src/main/java/org/example/catch_line/booking/reservation/controller/ReservationController.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/booking/waiting/controller/WaitingController.java
  src/main/java/org/example/catch_line/booking/waiting/service/WaitingService.java
  src/main/java/org/example/catch_line/dining/restaurant/model/mapper/RestaurantPreviewMapper.java
  src/main/java/org/example/catch_line/dining/restaurant/service/RestaurantPreviewService.java
  src/main/java/org/example/catch_line/exception/booking/WaitingException.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/history/model/mapper/HistoryMapper.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/notification/controller/NotificationController.java
  src/main/java/org/example/catch_line/notification/controller/NotificationRestController.java
  src/main/java/org/example/catch_line/notification/controller/readme.md
  src/main/java/org/example/catch_line/notification/model/dto/NotificationResponse.java
  src/main/java/org/example/catch_line/notification/model/dto/readme.md
  src/main/java/org/example/catch_line/notification/model/entity/NotificationEntity.java
  src/main/java/org/example/catch_line/notification/model/entity/readme.md
  src/main/java/org/example/catch_line/notification/repository/EmitterRepository.java
  src/main/java/org/example/catch_line/notification/repository/NotificationRepository.java
  src/main/java/org/example/catch_line/notification/repository/readme.md
  src/main/java/org/example/catch_line/notification/service/NotificationService.java
  src/main/java/org/example/catch_line/notification/service/readme.md
  src/main/java/org/example/catch_line/user/member/service/MyScrapService.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/resources/templates/notification/notification.html
  src/main/resources/templates/reservation/reservation.html
  src/main/resources/templates/waiting/waiting.html
  src/test/java/org/example/catch_line/booking/reservation/controller/ReservationControllerTest.java
  src/test/java/org/example/catch_line/booking/reservation/service/ReservationServiceTest.java
  src/test/java/org/example/catch_line/history/controller/HistoryControllerTest.java
Labels: enhancement, refactoring

#109 [Feature] 예약 동시성 테스트
  src/main/java/org/example/catch_line/booking/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/test/java/org/example/catch_line/concurrency/ConcurrencyTest2.java
  src/test/resources/application-test.properties
Labels: enhancement

#111 [Refactoring] 식당 코드 리팩토링
  src/main/java/org/example/catch_line/dining/menu/model/dto/MenuRequest.java
  src/main/java/org/example/catch_line/dining/menu/model/entity/MenuEntity.java
  src/main/java/org/example/catch_line/dining/menu/model/mapper/MenuMapper.java
  src/main/java/org/example/catch_line/dining/menu/model/validation/MenuValidator.java
  src/main/java/org/example/catch_line/dining/menu/service/MenuService.java
  src/main/java/org/example/catch_line/dining/restaurant/controller/RestaurantController.java
  src/main/java/org/example/catch_line/dining/restaurant/controller/RestaurantImageController.java
  src/main/java/org/example/catch_line/dining/restaurant/model/dto/RestaurantHourRequest.java
  src/main/java/org/example/catch_line/dining/restaurant/model/entity/RestaurantEntity.java
  src/main/java/org/example/catch_line/dining/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/dining/restaurant/model/entity/RestaurantImageEntity.java
  src/main/java/org/example/catch_line/dining/restaurant/model/mapper/RestaurantHourMapper.java
  src/main/java/org/example/catch_line/dining/restaurant/model/mapper/RestaurantMapper.java
  src/main/java/org/example/catch_line/dining/restaurant/repository/RestaurantRepository.java
  src/main/java/org/example/catch_line/dining/restaurant/service/RestaurantHourService.java
  src/main/java/org/example/catch_line/dining/restaurant/service/RestaurantImageService.java
  src/main/java/org/example/catch_line/dining/restaurant/service/RestaurantPreviewService.java
  src/main/java/org/example/catch_line/dining/restaurant/service/RestaurantService.java
  src/main/java/org/example/catch_line/dining/restaurant/validation/RestaurantValidator.java
  src/main/java/org/example/catch_line/exception/authorizaion/UnauthorizedException.java
  src/main/java/org/example/catch_line/exception/dining/MenuNotFoundException.java
  src/main/java/org/example/catch_line/exception/image/ImageNotFoundException.java
  src/main/java/org/example/catch_line/exception/review/ReviewNotFoundException.java
  src/main/java/org/example/catch_line/notification/model/dto/NotificationResponse.java
  src/main/java/org/example/catch_line/review/controller/ReviewController.java
  src/main/java/org/example/catch_line/review/model/entity/ReviewEntity.java
  src/main/java/org/example/catch_line/review/service/ReviewService.java
  src/main/java/org/example/catch_line/review/validation/ReviewValidator.java
  src/main/java/org/example/catch_line/scrap/controller/ScrapController.java
  src/main/java/org/example/catch_line/scrap/repository/ScrapRepository.java
  src/main/java/org/example/catch_line/scrap/service/ScrapService.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerService.java
  src/main/java/org/example/catch_line/user/owner/validation/OwnerValidator.java
  src/main/resources/templates/owner/restaurant.html
  src/test/java/org/example/catch_line/menu/service/MenuServiceTest.java
  src/test/java/org/example/catch_line/restaurant/service/RestaurantHourServiceTest.java
  src/test/java/org/example/catch_line/restaurant/service/RestaurantServiceTest.java
Labels: refactoring

#121 [Refactoring] Security Config 및 Authorization Filter 수정
  src/main/java/org/example/catch_line/config/SecurityConfig.java
  src/main/java/org/example/catch_line/filter/MemberJwtAuthorizationFilter.java
  src/main/java/org/example/catch_line/review/controller/ReviewController.java
  src/main/java/org/example/catch_line/user/member/controller/thymeleaf/MemberController.java
  src/main/resources/templates/member/login.html
Labels: enhancement, refactoring

#126 [Refactoring] Refactoring owner
  src/main/java/org/example/catch_line/booking/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/dining/menu/model/dto/MenuRequest.java
  src/main/java/org/example/catch_line/dining/restaurant/controller/RestaurantPreviewController.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/notification/model/dto/NotificationResponse.java
  src/main/java/org/example/catch_line/review/model/entity/ReviewEntity.java
  src/main/java/org/example/catch_line/user/member/model/dto/LoginRequest.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerAuthController.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerMenuController.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerRestaurantController.java
  src/main/java/org/example/catch_line/user/owner/model/dto/OwnerLoginRequest.java
  src/main/java/org/example/catch_line/user/owner/model/dto/OwnerResponse.java
  src/main/java/org/example/catch_line/user/owner/model/dto/OwnerSignUpRequest.java
  src/main/java/org/example/catch_line/user/owner/model/entity/OwnerEntity.java
  src/main/resources/templates/history/reservationDetail.html
  src/main/resources/templates/history/waitingDetail.html
  src/main/resources/templates/owner/menus.html
  src/main/resources/templates/owner/reservationDetail.html
  src/main/resources/templates/owner/restaurantList.html
  src/main/resources/templates/owner/restaurantListHistory.html
  src/main/resources/templates/owner/waitingDetail.html
Labels: refactoring

#127 [Feature] 통계 기능 구현
  src/main/java/org/example/catch_line/booking/reservation/repository/ReservationRepository.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/booking/waiting/repository/WaitingRepository.java
  src/main/java/org/example/catch_line/booking/waiting/service/WaitingService.java
  src/main/java/org/example/catch_line/dining/restaurant/validation/RestaurantValidator.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/statistics/controller/StatisticsController.java
  src/main/java/org/example/catch_line/statistics/model/dto/StatisticsGraphResponse.java
  src/main/java/org/example/catch_line/statistics/model/dto/StatisticsResponse.java
  src/main/java/org/example/catch_line/statistics/model/entity/StatisticsEntity.java
  src/main/java/org/example/catch_line/statistics/model/mapper/StatisticsMapper.java
  src/main/java/org/example/catch_line/statistics/repository/StatisticsRepository.java
  src/main/java/org/example/catch_line/statistics/service/StatisticsService.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/owner/owner.html
  src/main/resources/templates/statistics/statistics.html
Labels: enhancement

#130 [Refactoring] 통계, 웨이팅, 예약 리팩토링
  src/main/java/org/example/catch_line/booking/reservation/model/entity/ReservationEntity.java
  src/main/java/org/example/catch_line/booking/reservation/service/ReservationService.java
  src/main/java/org/example/catch_line/booking/waiting/model/entity/WaitingEntity.java
  src/main/java/org/example/catch_line/booking/waiting/service/WaitingService.java
  src/main/java/org/example/catch_line/history/validation/HistoryValidator.java
  src/main/java/org/example/catch_line/statistics/controller/StatisticsController.java
  src/main/java/org/example/catch_line/statistics/model/mapper/StatisticsMapper.java
  src/main/java/org/example/catch_line/statistics/repository/StatisticsRepository.java
  src/main/java/org/example/catch_line/statistics/service/StatisticsService.java
  src/main/resources/templates/statistics/statistics.html
Labels: refactoring

#141 [Refactoring] 전체 리팩토링 진행
  .gitignore
  src/main/java/org/example/catch_line/booking/reservation/controller/ReservationController.java
  src/main/java/org/example/catch_line/booking/waiting/controller/WaitingController.java
  src/main/java/org/example/catch_line/common/kakao/controller/AddressController.java
  src/main/java/org/example/catch_line/common/model/converter/EmailConverter.java
  src/main/java/org/example/catch_line/common/model/converter/PasswordConverter.java
  src/main/java/org/example/catch_line/common/model/converter/PhoneNumberConverter.java
  src/main/java/org/example/catch_line/common/session/RoleConst.java
  src/main/java/org/example/catch_line/common/session/SessionUtils.java
  src/main/java/org/example/catch_line/dining/restaurant/README.md
  src/main/java/org/example/catch_line/dining/restaurant/controller/RestaurantImageController.java
  src/main/java/org/example/catch_line/dining/restaurant/controller/RestaurantPreviewController.java
  src/main/java/org/example/catch_line/dining/restaurant/model/entity/RestaurantHourEntity.java
  src/main/java/org/example/catch_line/dining/restaurant/repository/RestaurantHourRepository.java
  src/main/java/org/example/catch_line/dining/restaurant/repository/RestaurantRepository.java
  src/main/java/org/example/catch_line/dining/restaurant/validation/RestaurantValidator.java
  src/main/java/org/example/catch_line/exception/CatchLineException.java
  src/main/java/org/example/catch_line/exception/GlobalExceptionHandler.java
  src/main/java/org/example/catch_line/exception/README.md
  src/main/java/org/example/catch_line/exception/booking/ReservationException.java
  src/main/java/org/example/catch_line/exception/booking/WaitingException.java
  src/main/java/org/example/catch_line/exception/dining/RestaurantHourNotFoundException.java
  src/main/java/org/example/catch_line/exception/dining/RestaurantNotFoundException.java
  src/main/java/org/example/catch_line/exception/email/DuplicateEmailException.java
  src/main/java/org/example/catch_line/exception/password/InvalidEncodedPasswordException.java
  src/main/java/org/example/catch_line/exception/session/InvalidSessionException.java
  src/main/java/org/example/catch_line/exception/user/DuplicateOwnerLoginIdException.java
  src/main/java/org/example/catch_line/exception/user/MemberNotFoundException.java
  src/main/java/org/example/catch_line/exception/user/OwnerNotFoundException.java
  src/main/java/org/example/catch_line/history/controller/HistoryController.java
  src/main/java/org/example/catch_line/history/model/mapper/HistoryMapper.java
  src/main/java/org/example/catch_line/history/service/HistoryService.java
  src/main/java/org/example/catch_line/history/validation/HistoryValidator.java
  src/main/java/org/example/catch_line/notification/controller/NotificationRestController.java
  src/main/java/org/example/catch_line/notification/model/dto/NotificationResponse.java
  src/main/java/org/example/catch_line/notification/service/NotificationService.java
  src/main/java/org/example/catch_line/review/controller/ReviewController.java
  src/main/java/org/example/catch_line/user/auth/service/OwnerLoginService.java
  src/main/java/org/example/catch_line/user/member/controller/MyReviewController.java
  src/main/java/org/example/catch_line/user/member/controller/MyScrapController.java
  src/main/java/org/example/catch_line/user/member/model/dto/MemberDeleteResponse.java
  src/main/java/org/example/catch_line/user/member/model/dto/SignUpResponse.java
  src/main/java/org/example/catch_line/user/member/model/mapper/MemberResponseMapper.java
  src/main/java/org/example/catch_line/user/member/model/provider/validation/MemberValidator.java
  src/main/java/org/example/catch_line/user/member/model/provider/validation/PasswordValidator.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerAuthController.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerController.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerMenuController.java
  src/main/java/org/example/catch_line/user/owner/controller/OwnerRestaurantController.java
  src/main/java/org/example/catch_line/user/owner/model/dto/OwnerResponse.java
  src/main/java/org/example/catch_line/user/owner/model/entity/OwnerEntity.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerAuthService.java
  src/main/java/org/example/catch_line/user/owner/service/OwnerService.java
  src/main/java/org/example/catch_line/user/owner/validation/OwnerValidator.java
  src/main/resources/templates/owner/menus.html
  src/main/resources/templates/owner/updateRestaurant.html
  src/test/java/org/example/catch_line/concurrency/ConcurrencyTest2.java
  src/test/java/org/example/catch_line/restaurant/controller/RestaurantControllerTest.java
  src/test/java/org/example/catch_line/restaurant/controller/RestaurantPreviewControllerTest.java
Labels: refactoring

#147 [Refactoring] 회원가입 시 검증 placeholder로 표시
  src/main/resources/templates/member/memberUpdate.html
  src/main/resources/templates/member/signup.html
Labels: refactoring
